server:
  port: 9080
spring:
  session:
    ignite:
      defaultMaxInactiveInterval: 180
      cacheName: spring.session.cache
ignite-client:
  addresses: 127.0.0.1:10800 # this is mandatory property!
  timeout: 10000
  tcpNoDelay: false
